# gc-termtest-C.pl
use List::Util 'shuffle';

# round(runif(50,999999.5,9999999.5),0)
@seed=(
"6115106",
"4458352",
"4824915",
"7481256",
"1240486",
"8929712",
"9952218",
"4989765",
"2284686",
"9931308",
"5912840",
"3903347",
"6265910",
"1514605",
"4308856",
"7275789",
"2596263",
"7911112",
"1205361",
"2005506",
"5940815",
"5088095",
"1925569",
"6953980",
"2495016",
"1444195",
"3505611",
"2641570",
"2266736",
"6513845",
"7455149",
"3770263",
"8390824",
"3786564",
"3094608",
"7232933",
"9924671",
"3290431",
"8241726",
"8254946",
"4828353",
"9381326",
"6652952",
"7318252",
"1987123",
"4009287",
"1234320",
"6088281",
"1513202",
"4292859"
    );

srand($seed[1]);

# Protter and Protter, page 224, example 2
$aufgabe[0]=sub {
    print termtest "The two curves \$y=x\$ and \$y=x^{3}\$ meet three times; call the three points of intersection \$A,B,\$ and \$C\$, from left to right. Find the area between the two curves between \$A\$ and \$C\$. If part of this area is below the \$x\$-axis, make sure to \\emph{add} it to the total area and not \\emph{subtract} it.\n";
};

# Protter and Protter, page 232, exercise 27 and 28
$aufgabe[1]=sub {
    print termtest "\$S\$ is a solid generated by revolving a bounded region \$R\$ about the \$x\$-axis. Find the volume of \$S\$. \$R\$ is bounded by the $v001[$i1]. $v007[$i1]\n";
};

# Protter and Protter, page 245, example 3
$aufgabe[2]=sub {
    print termtest "Find the area of the surface generated by revolving about the \$y\$-axis the arc \$C\$ given by\n\\begin{equation}\n\\label{eq:aiquuojo}\nx=$v008[$i1]\\sqrt{\\frac{y}{$v009[$i1]}},1\\leq{}y\\leq{}2\n\\end{equation}\n";
};

$aufgabe[3]=sub {
    # Protter and Protter, page 241, exercises 9 and 11 --> too difficult
    # print termtest "Find the following arc length.\n\\begin{equation}\n\\label{eq:eedookuo}\n$v002[$i1]\n\\end{equation}\n";
    print termtest "Find the length of the following curve:\\begin{equation}y=\\frac{1}{3}\\left(x^{2}+2\\right)^{\\frac{3}{2}}\\mbox{ from  }x=0\\mbox{ to }x=3\\notag\\end{equation}\n";
};

$aufgabe[4]=sub {
    # print termtest "Evaluate the following integral.\n\\begin{equation}\n\\label{eq:teingahg}\n\\int_{$v005[$i1]}^{$v006[$i1]}$v003[$i1]^{3}$v004[$i1]t\\,dt\n\\end{equation}\n";
    print termtest "Breathing is cyclic and a full respiratory cycle from the beginning of inhalation to the end of exhalation takes about 5 seconds. The maximum rate of air flow into the lungs is about 0.5 litres per second. This explains, in part, why the function\n\\begin{equation}\nf(t)=\\frac{1}{2}\\sin\\left(\\frac{2\\pi}{5}t\\right)\n\\end{equation}\nhas often been used to model the rate of air flow into the lungs. Use this model to find the volume of inhaled air in the lungs at time \$t\$.\n";
};

$aufgabe[5]=sub {
    print termtest "Find the length of the following curve.\n\\begin{equation}\ny=\\int_{0}^{x}\\sqrt{\\sec^{4}t-1}\\,dt,-\\frac{\\pi}$v010[$i1]\\leq{}x\\leq\\frac{\\pi}$v010[$i1]\n\\end{equation}\nRemember that according to the Fundamental Theorem of Calculus, if \$g(x)=\\int_{a}^{x}f(t)\\,dt\$, then \$g'(x)=f(x)\$.\n";
};

$aufgabe[6]=sub {
    # print termtest "Use integration by parts to find the following integral. Remember that you can find the antiderivative of \$f(x)=\\ln{}x\$ by writing \$f(x)=\\ln{}x\\cdot{}1\$ and then integrating by parts.\n\\begin{equation}\n\\label{eq:nophieyu}\\int\\left(\\ln{}x\\right)^{2}\\,dx\n\\end{equation}\n";
    print termtest "Use the substitution \$u=\\sqrt{x}+1\$ to evaluate the definite integral\n\\begin{equation}\n\\int_{4}^{1}\\frac{(\\sqrt{x}+1)^{4}}{2\\sqrt{x}}\\,dx\n\\end{equation}\n";
};

for ($y2=0;$y2<=$#aufgabe;++$y2)
{
    $z5=rand;
    $z1[$y2]=$z5.";;"."$y2";
}
    @z3=sort(@z1);
for ($y4=0;$y4<=$#z3;++$y4)
{
    @z4=split(/;;/,$z3[$y4]);
    $z2[$y4]=$z4[1];
}

$nm[0]="termtest1";
$nm[1]="termtest2";

$vn[0]="1";
$vn[1]="2";

$v001[0]="lines \$y=0\$, \$x=\\pi/6\$, \$x=\\pi/4\$, and the curve \$y=\\cos{}x\$";
$v002[0]="y=\\frac{1}{8}x^{4}+\\frac{1}{4}x^{-2},1\\leq{}x\\leq{}2";
$v003[0]="\\cos";
$v004[0]="2";
$v005[0]="\\frac{\\pi}{6}";
$v006[0]="\\frac{\\pi}{4}";
$v007[0]="You may want to use integral 66 from Thomas' Brief Table of Integrals,\n\\begin{equation}\n\\int\\cos^{2}ax\\,dx=\\frac{x}{2}+\\frac{\\sin{}2ax}{4a}+C\n\\end{equation}";
$v008[0]="2";
$v009[0]="3";
$v010[0]="3";
$v011[0]="";
$v012[0]="";
$v013[0]="";
$v014[0]="";
$v015[0]="";
$v016[0]="";
$v017[0]="";
$v018[0]="";

$v001[1]="lines \$y=0\$, \$x=\\pi/6\$, \$x=\\pi/3\$, and the curve \$y=\\tan{}x\$";
$v002[1]="y=\\frac{1}{4}x^{5}+\\frac{1}{15}x^{-3},2\\leq{}x\\leq{}3";
$v003[1]="\\sin";
$v004[1]="3";
$v005[1]="\\frac{\\pi}{12}";
$v006[1]="\\frac{\\pi}{6}";
$v007[1]="You may want to use the trigonometric identity \$1+\\tan^{2}\\vartheta=\\sec^{2}\\vartheta\$. ";
$v008[1]="3";
$v009[1]="2";
$v010[1]="4";
$v011[1]="";
$v012[1]="";
$v013[1]="";
$v014[1]="";
$v015[1]="";
$v016[1]="";
$v017[1]="";
$v018[1]="";

$p[0]="5";
$p[1]="5";
$p[2]="5";
$p[3]="5";
$p[4]="5";
$p[5]="5";
$p[6]="5";

for ($i1=0;$i1<=$#nm;++$i1)
{
open(termtest,">./gc-termtest-C$vn[$i1].tex");
print termtest "% gc-termtest-C.tex\n\n";
print termtest "\\documentclass[11pt]{article}\n";
print termtest "\\usepackage{alltt}\n";
print termtest "\\usepackage{enumerate}\n";
print termtest "\\usepackage{syllogism} \n";
print termtest "\\usepackage{october}\n";
print termtest "\\usepackage[table]{xcolor}\n";
print termtest "\\pagestyle{empty}\n\n";
print termtest "\\newcounter{aufg}\n";
print termtest "\\setcounter{aufg}{0}\n";
print termtest "\\newcommand{\\aufgabe}[1]{\\refstepcounter{aufg}\\textbf{(\\arabic{aufg})}[#1 points]}\n\n";

print termtest "\\begin{document}\n\n";

print termtest "\\textbf{Term Test C version $vn[$i1]}\n\n";
print termtest "Note that for \$f(x)=\\tan{}x\$ the derivative is \$f'(x)=\\sec^{2}x\$.\n\n";

@bufgabe=shuffle(@aufgabe);

for ($i2=0;$i2<=$#aufgabe;++$i2)
{
    print termtest "\\aufgabe{$p[$i2]} ";
    $bufgabe[$i2]->();
    print termtest "\n";
}

print termtest "\\end{document}\n";
close(termtest);
}
