./india.pl gc-03-BasicDiff
./india.pl gc-04-ProductQuotient
./india.pl gc-05-TrigDiff
./india.pl gc-06-ChainRule
./india.pl gc-07-HigherOrder
./india.pl gc-08-Applications
./india.pl gc-09-Analyzing
./india.pl gc-10-Hyperbolic
./india.pl gc-11-OptimizationNewton
./india.pl gc-12-Fundamental
./india.pl gc-13-AreaVolume
./india.pl gc-14-IntMeth
./india.pl gc-15-IntLab
./india.pl gc-15-Taylor
./india.pl gc-16-3d
./india.pl gc-lab-01-limits
