(TeX-add-style-hook
 "gc-14-IntMeth"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("beamer" "xcolor=dvipsnames")))
   (add-to-list 'LaTeX-verbatim-environments-local "alltt")
   (add-to-list 'LaTeX-verbatim-environments-local "semiverbatim")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "beamer"
    "beamer10"
    "teachbeamer")
   (LaTeX-add-labels
    "eq:deixugha"
    "eq:eetusiil"
    "eq:ohshaoxe"
    "eq:eevieweo"
    "eq:ushooxiu"
    "eq:olaihaxi"
    "eq:eenoophu"
    "eq:iachuejo"
    "eq:diacheiv"
    "eq:shaixeen"
    "eq:eileevar"
    "eq:lumuewah"
    "eq:waethish"
    "eq:anguyaeh"
    "eq:jiucaing"
    "eq:eisohmie"
    "eq:aibeajuh"
    "eq:eeroteda"
    "eq:eekahchi"
    "eq:mauphouw"
    "eq:pahteeth"
    "eq:ceiquoor"
    "eq:riweevie"
    "eq:aigighau"
    "eq:omixughu"
    "eq:baemixeg"
    "eq:aeteepah"
    "eq:loocooch"
    "eq:eewuquex"
    "eq:bahyathe"
    "eq:xohphohh"
    "eq:mixausho"
    "eq:ohleseej"
    "eq:aigeishu"
    "eq:zeecogoo"
    "eq:roogheis"
    "eq:ohjomopu"
    "eq:feecheir"
    "eq:dahcohne"
    "eq:uokaivie"
    "eq:taxeepei"
    "eq:theijaeg"
    "eq:phahpiqu"
    "eq:beidahch"
    "eq:auzoowoo"
    "eq:vieyaigh"
    "eq:aiphithe"
    "eq:taebohme"
    "eq:eecahquo"
    "eq:aebashiy"
    "eq:oiwuilah"
    "eq:xoocheix"
    "eq:eimejief"
    "eq:oizaixea"
    "eq:nohceira"
    "eq:aemahjoo"
    "eq:iepheith"
    "eq:oghufohx"
    "eq:zephulai"
    "eq:joochupa"
    "eq:siengoel"
    "eq:daejeile"
    "eq:ielahghu"
    "eq:einahkur"
    "eq:owamaela"
    "eq:acahjahj"
    "eq:cohnalee"
    "eq:aoyoodof"
    "eq:hezaifoo"
    "eq:uophaequ"
    "eq:uupheilu"
    "eq:uejahgai"
    "eq:ufiurugo"
    "eq:iepahgai"
    "eq:koquohge"
    "eq:thaemooc"
    "eq:noojoosh"
    "eq:xaikieji"
    "eq:cichacah"
    "eq:rifiedoh"
    "eq:phiethee"
    "eq:oorighoe"
    "eq:vaewahsh"
    "eq:moochofe"
    "eq:feirueho"
    "eq:ietahpha"
    "eq:saeheing"
    "eq:haedeeli"
    "eq:oxeiyooh"
    "eq:oaruveep"
    "eq:eefeishe"
    "eq:cheifiwo"
    "eq:eiquiena"
    "eq:yielohwi"
    "eq:oocoibuo"
    "eq:eebaesie"
    "eq:aezihuth"
    "eq:wiexohje"))
 :latex)

