(TeX-add-style-hook
 "gc-15-Taylor"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("beamer" "xcolor=dvipsnames")))
   (add-to-list 'LaTeX-verbatim-environments-local "alltt")
   (add-to-list 'LaTeX-verbatim-environments-local "semiverbatim")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "beamer"
    "beamer10"
    "teachbeamer")
   (LaTeX-add-labels
    "eq:tahxooke"
    "eq:ahngahph"
    "eq:eeyengog"
    "eq:seciefai"
    "eq:oobeecho"
    "eq:ohjaihen"
    "eq:aedairoy"
    "eq:eechuwee"
    "eq:pomahwus"
    "eq:tahsaepi"
    "eq:xahhusaj"
    "eq:vaetoegh"
    "eq:ekiesohj"
    "eq:lohwoquo"
    "eq:zaquadao"
    "eq:eiphohng"
    "eq:ierohghu"
    "eq:uunguexo"
    "eq:quaejich"
    "eq:aijeetha"
    "eq:axohthee"
    "eq:amoofugh"
    "eq:aegahiox"
    "eq:iopheigh"
    "eq:paipawai"
    "eq:aiphohai"
    "eq:yeefieth"
    "eq:jaifahti"
    "eq:oosuphif"
    "eq:epeiveix"
    "eq:bauveeze"
    "eq:uithaezi"
    "eq:voomeijo"
    "eq:oageevae"
    "eq:phoewahg"
    "eq:ziegaequ"
    "eq:ezahraox"
    "eq:queiquai"
    "eq:taingaik"
    "eq:aephieng"
    "eq:oopoosoo"
    "eq:quaejash"
    "eq:eaquaish"
    "eq:ejeixuaj"
    "eq:aeteiroh"
    "eq:lahyaxee"
    "eq:uaxahphe"
    "eq:aegeigho"
    "eq:aighuhif"
    "eq:pheequie"
    "eq:uaqueigh"
    "eq:eecizaja"
    "eq:coojudie"
    "eq:aengooph"
    "eq:eghoocah"
    "eq:xalaixii"
    "eq:ohmaekel"
    "eq:iechaefi"
    "eq:aibooqui"
    "eq:tohpojos"
    "eq:queiroxu"
    "eq:quewahre"
    "eq:axoochid"
    "eq:kahfeipe"
    "eq:jeepaipe"
    "eq:itaivaeg"
    "eq:ahthoazo"
    "eq:ahazohve"
    "eq:oolietai"
    "eq:cutailae"
    "eq:oetaenis"
    "eq:ikooveiv"
    "eq:ohyoobip"
    "eq:tolokaav"
    "eq:chaithie"
    "eq:oorohkao"
    "eq:foigacoo"
    "eq:sishahgh"
    "eq:eighetog"
    "eq:oxishait"
    "eq:chuyeeye"
    "eq:queiyuif"
    "eq:aoyahphe"
    "eq:ahtoilei"))
 :latex)

